[workspace]
resolver = "2"
members = [
    "logfs",
    "logfs_cli",
]

[workspace.package]
authors = ["Christoph Herzog <chris@theduke.at>"]
readme = "README.md"
keywords = [
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/theduke/logfs"
edition = "2024"
rust-version = "1.85"
